### ISSUE TITLE
util.py attempts illegal hg command

### ISSUE THREAD

**Issue by mykter** [mozilla-services/mopytools#4]
line 263 of util.py sets the vcs command as:
  cmd = 'hg up -c'

-c isn't a valid mercurial option, so when this is hit it falls over. I hit this running "make build" for the sync server.

**Comment by rfk** [comment]
What version of mercurial are you using?  The `update` command in my hg v2.0.2 supports both "-c" and "-C" options.  Can you please post a traceback of the error you receive?

**Comment by mykter** [comment]
Mercurial 1.0.1
make build

< snip: lots of successful package downloads etc >

Cleaning up...
bin/buildapp -c prod -i http://pypi.python.org/simple server-core,server-reg,server-storage
The current channel is prod.
Building the app 
  Checking the environ                                                                         [ok]
  Updating the repo 'hg up -c -r "rpm-1.0-3"' failed with code 255
hg update [-C] [-d DATE] [[-r] REV]

< snip: hg help, including
 options:
  -C --clean  overwrite locally modified files
 end snip >

hg update: option -c not recognized

[fail]                                                                                               [fail]
make: **\* [build] Error 255

**Comment by rfk** [comment]
> Mercurial 1.0.1

Wow, this version of mercurial was released in May 2008.  Unfortunately, I don't think it's realistic for us support mercurial versions this old.

The -c/--check option was added in mercurial 1.3.  Please update your version of mercurial and try again.
